// <auto-generated />
using System;
using GameStore.Dal.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameStore.Dal.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    [Migration("20200922151229_InitialCreateDb")]
    partial class InitialCreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GameStore.Dal.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Good game!",
                            GameId = 1,
                            IsDeleted = false,
                            Name = "Peter",
                            ParentCommentId = 0,
                            Time = new DateTime(2020, 7, 20, 12, 22, 28, 73, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Body = "Peter, Thanks a lot)",
                            GameId = 1,
                            IsDeleted = false,
                            Name = "Adam",
                            ParentCommentId = 1,
                            Time = new DateTime(2020, 7, 20, 12, 22, 28, 73, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Body = "Peter, cool!",
                            GameId = 1,
                            IsDeleted = false,
                            Name = "Bogdan from Bolt",
                            ParentCommentId = 1,
                            Time = new DateTime(2020, 7, 20, 12, 22, 28, 73, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            Body = "Adam, yep))0)",
                            GameId = 1,
                            IsDeleted = false,
                            Name = "Kelvin",
                            ParentCommentId = 2,
                            Time = new DateTime(2020, 7, 20, 12, 22, 28, 73, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            Body = "Adam++",
                            GameId = 1,
                            IsDeleted = false,
                            Name = "Martin",
                            ParentCommentId = 2,
                            Time = new DateTime(2020, 7, 20, 12, 22, 28, 73, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("GameStore.Dal.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Discontinued")
                        .HasColumnType("bit");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<short>("UnitInStock")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("PublisherId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = @"The Witcher: Wild Hunt is a story-driven open world RPG set in a visually stunning fantasy universe full of meaningful choices and impactful consequences. In The Witcher, you play as professional monster hunter Geralt of Rivia tasked with finding a child of prophecy in a vast open world rich with merchant cities, pirate islands, dangerous mountain passes, and forgotten caverns to explore. 

KEY FEATURES: 
PLAY AS A HIGHLY TRAINED MONSTER SLAYER FOR HIRE 
Trained from early childhood and mutated to gain superhuman skills, strength and reflexes, witchers are a counterbalance to the monster-infested world in which they live. 

	Gruesomely destroy foes as a professional monster hunter armed with a range of upgradeable weapons, mutating potions and combat magic. 
	Hunt down a wide range of exotic monsters — from savage beasts prowling the mountain passes, to cunning supernatural predators lurking in the shadows of densely populated towns. 
	Invest your rewards to upgrade your weaponry and buy custom armour, or spend them away in horse races, card games, fist fighting, and other pleasures the night brings.",
                            Discontinued = false,
                            Discount = 7f,
                            IsDeleted = false,
                            Key = "The Witcher 3: Wild Hunt",
                            Name = "The Witcher 3: Wild Hunt",
                            Price = 12.00m,
                            PublisherId = 1,
                            UnitInStock = (short)10
                        },
                        new
                        {
                            Id = 2,
                            Description = @"Indebted to the wrong people,with his life on the line,veteran of the U.S.Cavalry and now hired gun,Booker DeWitt has only one opportunity to wipe his slate clean.He must rescue Elizabeth,a mysterious girl imprisoned since childhood and locked up in the flying city of Columbia.Forced to trust one another,Booker and Elizabeth form a powerful bond during their daring escape. Together,they learn to harness an expanding arsenal of weapons and abilities, as they fight on zeppelins in the clouds,along high - speed Sky - Lines,and down in the streets of Columbia,all while surviving the threats of the air - city and uncovering its dark secret. 

Key Features
	The City in the Sky – Leave the depths of Rapture to soar among the clouds of Columbia. A technological marvel, the flying city is a beautiful and vibrant world that holds a very dark secret. 
	Unlikely Mission – Set in 1912, hired gun Booker DeWitt must rescue a mysterious girl from the sky-city of Columbia or never leave it alive. 
	Whip, Zip, and Kill – Turn the city’s Sky-Lines into weaponized roller coasters as you zip through the flying city and dish out fatal hands-on punishment.
	Tear Through Time – Open Tears in time and space to shape the battlefield and turn the tide in combat by pulling weapons, turrets, and other resources out of thin air.
	Vigorous Powers – Throw explosive fireballs, shoot lightning, and release murders of crows as devastatingly powerful Vigors surge through your body to be unleashed against all that oppose you.
	Custom Combat Experience – With deadly weapons in one hand, powerful Vigors in the other, and the ability to open Tears in time and space, fight your own way through the floating city of Columbia to rescue Elizabeth and reach freedom.
	1999 Mode – Upon finishing BioShock Infinite, the player can unlock a game mode called “1999 Mode” that gives experienced players a taste of the kind of design and balance that hardcore gamers enjoyed back in the 20th century.",
                            Discontinued = false,
                            Discount = 6f,
                            IsDeleted = false,
                            Key = "BioShock Infinite",
                            Name = "BioShock Infinite",
                            Price = 12.01m,
                            PublisherId = 1,
                            UnitInStock = (short)11
                        },
                        new
                        {
                            Id = 3,
                            Description = "The forest of Nibel is dying. After a powerful storm sets a series of devastating events in motion, an unlikely hero must journey to find his courage and confront a dark nemesis to save his home. “Ori and the Blind Forest” tells the tale of a young orphan destined for heroics, through a visually stunning action-platformer crafted by Moon Studios for PC. Featuring hand-painted artwork, meticulously animated character performance, and a fully orchestrated score, “Ori and the Blind Forest” explores a deeply emotional story about love and sacrifice, and the hope that exists in us all. ",
                            Discontinued = false,
                            Discount = 2f,
                            IsDeleted = false,
                            Key = "Ori and the Blind Forest: Definitive Edition",
                            Name = "Ori and the Blind Forest: Definitive Edition",
                            Price = 11.40m,
                            PublisherId = 1,
                            UnitInStock = (short)1
                        },
                        new
                        {
                            Id = 4,
                            Description = @"RimWorld is a sci-fi colony sim driven by an intelligent AI storyteller. Inspired by Dwarf Fortress, Firefly, and Dune. 

You begin with three survivors of a shipwreck on a distant world.
	Manage colonists' moods, needs, wounds, illnesses and addictions.
	Build in the forest, desert, jungle, tundra, and more.
	Watch colonists develop and break relationships with family members, lovers, and spouses.
	Replace wounded limbs and organs with prosthetics, bionics, or biological parts harvested from others.
	Fight pirates, tribes, mad animals, giant insects and ancient killing machines.
	Craft structures, weapons, and apparel from metal, wood, stone, cloth, and futuristic materials.
	Tame and train cute pets, productive farm animals, and deadly attack beasts.
	Trade with passing ships and caravans.
	Form caravans to complete quests, trade, attack other factions, or migrate your whole colony.
	Dig through snow, weather storms, and fight fires.
	Capture refugees or prisoners and turn them to your side or sell them into slavery.
	Discover a new generated world each time you play.
	Explore hundreds of wild and interesting mods on the Steam Workshop.
	Learn to play easily with the help of an intelligent and unobtrusive AI tutor.

RimWorld is a story generator.It’s designed to co-author tragic, twisted, and triumphant stories about imprisoned pirates, desperate colonists, starvation and survival. It works by controlling the “random” events that the world throws at you.Every thunderstorm, pirate raid, and traveling salesman is a card dealt into your story by the AI Storyteller. There are several storytellers to choose from. Randy Random does crazy stuff, Cassandra Classic goes for rising tension, and Phoebe Chillax likes to relax.

Your colonists are not professional settlers – they’re crash - landed survivors from a passenger liner destroyed in orbit. You can end up with a nobleman, an accountant, and a housewife. You’ll acquire more colonists by capturing them in combat and turning them to your side, buying them from slave traders, or taking in refugees. So your colony will always be a motley crew.

Each person’s background is tracked and affects how they play. A nobleman will be great at social skills(recruiting prisoners, negotiating trade prices), but refuse to do physical work. A farm oaf knows how to grow food by long experience, but cannot do research. A nerdy scientist is great at research, but cannot do social tasks at all. A genetically engineered assassin can do nothing but kill – but he does that very well.Colonists develop - and destroy - relationships. Each has an opinion of the others, which determines whether they'll become lovers, marry, cheat, or fight. Perhaps your two best colonists are happily married - until one of them falls for the dashing surgeon who saved her from a gunshot wound.The game generates a whole planet from pole to equator. You choose whether to land your crash pods in a cold northern tundra, a parched desert flat, a temperate forest, or a steaming equatorial jungle. Different areas have different animals, plants, diseases, temperatures, rainfall, mineral resources, and terrain. These challenges of surviving in a disease-infested, choking jungle are very different from those in a parched desert wasteland or a frozen tundra with a two - month growing season. 

Travel across the planet. You're not stuck in one place. You can form a caravan of people, animals, and prisoners. Rescue kidnapped former allies from pirate outposts, attend peace talks, trade with other factions, attack enemy colonies, and complete other quests. You can even pack up your entire colony and move to a new place. You can use rocket-powered transport pods to travel faster. 

You can tame and train animals. Lovable pets will cheer up sad colonists. Farm animals can be worked, milked, and sheared. Attack beasts can be released upon your enemies. There are many animals - cats, labrador retrievers, grizzly bears, camels, cougars, chinchillas, chickens, and exotic alien - like lifeforms. 

People in RimWorld constantly observe their situation and surroundings in order to decide how to feel at any given moment. They respond to hunger and fatigue, witnessing death, disrespectfully unburied corpses, being wounded, being left in darkness, getting packed into cramped environments, sleeping outside or in the same room as others, and many other situations. If they're too stressed, they might lash out or break down.

Wounds, infections, prosthetics, and chronic conditions are tracked on each body part and affect characters' capacities. Eye injuries make it hard to shoot or do surgery. Wounded legs slow people down. Hands, brain, mouth, heart, liver, kidneys, stomach, feet, fingers, toes, and more can all be wounded, diseased, or missing, and all have logical in-game effects. And other species have their own body layouts - take off a deer's leg, and it can still hobble on the other three. Take off a rhino's horn, and it's much less dangerous.

You can repair body parts with prosthetics ranging from primitive to transcendent. A peg leg will get Joe Colonist walking after an unfortunate incident with a rhinoceros, but he'll still be quite slow. Buy an expensive bionic leg from a trader the next year, and Joe becomes a superhuman runner. You can even extract, sell, buy, and transplant internal organs.",
                            Discontinued = false,
                            Discount = 3f,
                            IsDeleted = false,
                            Key = "RimWorld",
                            Name = "RimWorld",
                            Price = 12.11m,
                            PublisherId = 1,
                            UnitInStock = (short)3
                        },
                        new
                        {
                            Id = 5,
                            Description = @"Brave the Depths of a Forgotten Kingdom
Beneath the fading town of Dirtmouth sleeps an ancient,ruined kingdom. Many are drawn below the surface, searching for riches, or glory, or answers to old secrets.

Hollow Knight is a classically styled 2D action adventure across a vast interconnected world. Explore twisting caverns, ancient cities and deadly wastes; battle tainted creatures and befriend bizarre bugs; and solve ancient mysteries at the kingdom's heart.

Game Features
	Classic side-scrolling action, with all the modern trimmings.
	Tightly tuned 2D controls. Dodge, dash and slash your way through even the most deadly adversaries.
	Explore a vast interconnected world of forgotten highways, overgrown wilds and ruined cities.
	Forge your own path!The world of Hallownest is expansive and open. Choose which paths you take, which enemies you face and find your own way forward. 
	Evolve with powerful new skills and abilities! Gain spells, strength and speed. Leap to new heights on ethereal wings. Dash forward in a blazing flash. Blast foes with fiery Soul!
	Equip Charms! Ancient relics that offer bizarre new powers and abilities. Choose your favourites and make your journey unique!
	An enormous cast of cute and creepy characters all brought to life with traditional 2D frame - by - frame animation.
	Over 130 enemies! 30 epic bosses! Face ferocious beasts and vanquish ancient knights on your quest through the kingdom. Track down every last twisted foe and add them to your Hunter's Journal!
	Leap into minds with the Dream Nail. Uncover a whole other side to the characters you meet and the enemies you face.
	Beautiful painted landscapes, with extravagant parallax, give a unique sense of depth to a side - on world.
	Chart your journey with extensive mapping tools. Buy compasses, quills, maps and pins to enhance your understanding of Hollow Knight’s many twisting landscapes.
	A haunting, intimate score accompanies the player on their journey, composed by Christopher Larkin. The score echoes the majesty and sadness of a civilisation brought to ruin.
	Complete Hollow Knight to unlock Steel Soul Mode, the ultimate challenge!

An Evocative Hand-Crafted World
The world of Hollow Knight is brought to life in vivid, moody detail, its caverns alive with bizarre and terrifying creatures, each animated by hand in a traditional 2D style. Every new area you’ll discover is beautifully unique and strange, teeming with new creatures and characters. Take in the sights and uncover new wonders hidden off of the beaten path.If you like classic gameplay, cute but creepy characters, epic adventure and beautiful, gothic worlds, then Hollow Knight awaits!",
                            Discontinued = false,
                            Discount = 4f,
                            IsDeleted = false,
                            Key = "Hollow Knight",
                            Name = "Hollow Knight",
                            Price = 1.20m,
                            PublisherId = 1,
                            UnitInStock = (short)102
                        },
                        new
                        {
                            Id = 6,
                            Description = @"Portal 2 draws from the award-winning formula of innovative gameplay, story, and music that earned the original Portal over 70 industry accolades and created a cult following. 
The single - player portion of Portal 2 introduces a cast of dynamic new characters,a host of fresh puzzle elements, and a much larger set of devious test chambers. Players will explore never - before - seen areas of the Aperture Science Labs and be reunited with GLaDOS, the occasionally murderous computer companion who guided them through the original game.
The game’s two - player cooperative mode features its own entirely separate campaign with a unique story,test chambers, and two new player characters. This new mode forces players to reconsider everything they thought they knew about portals. Success will require them to not just act cooperatively, but to think cooperatively. 

Product Features 
	Extensive single player: Featuring next generation gameplay and a wildly - engrossing story.
	Complete two - person co - op: Multiplayer game featuring its own dedicated story, characters, and gameplay.
	Advanced physics: Allows for the creation of a whole new range of interesting challenges, producing a much larger but not harder game.
	Original music.
	Massive sequel: The original Portal was named 2007's Game of the Year by over 30 publications worldwide.
	Editing Tools: Portal 2 editing tools will be included.",
                            Discontinued = false,
                            Discount = 70f,
                            IsDeleted = false,
                            Key = "Portal 2",
                            Name = "Portal 2",
                            Price = 21.02m,
                            PublisherId = 1,
                            UnitInStock = (short)13
                        },
                        new
                        {
                            Id = 7,
                            Description = @"Congratulations.
The October labor lottery is complete.Your name was pulled. For immediate placement, report to the Ministry of Admission at Grestin Border Checkpoint. An apartment will be provided for you and your family in East Grestin. Expect a Class - 8 dwelling.
 Glory to Arstotzka

The communist state of Arstotzka has just ended a 6 - year war with neighboring Kolechia and reclaimed its rightful half of the border town, Grestin.Your job as immigration inspector is to control the flow of people entering the Arstotzkan side of Grestin from Kolechia. Among the throngs of immigrants and visitors looking for work are hidden smugglers, spies, and terrorists. Using only the documents provided by travelers and the Ministry of Admission's primitive inspect, search, and fingerprint systems you must decide who can enter Arstotzka and who will be turned away or arrested.",
                            Discontinued = false,
                            Discount = 9f,
                            IsDeleted = false,
                            Key = "Papers, Please",
                            Name = "Papers, Please",
                            Price = 12.10m,
                            PublisherId = 1,
                            UnitInStock = (short)19
                        },
                        new
                        {
                            Id = 8,
                            Description = @"Batman: Arkham City builds upon the intense, atmospheric foundation of Batman: Arkham Asylum, sending players flying through the expansive Arkham City - five times larger than the game world in Batman: Arkham Asylum - the new maximum security ""home"" for all of Gotham City's thugs, gangsters and insane criminal masterminds. Featuring an incredible Rogues Gallery of Gotham City's most dangerous criminals including Catwoman, The Joker, The Riddler, Two-Face, Harley Quinn, The Penguin, Mr. Freeze and many others, the game allows players to genuinely experience what it feels like to be The Dark Knight delivering justice on the streets of Gotham City.
Batman: Arkham City - Game of the Year Edition includes the following DLC:
	Catwoman Pack
	Nightwing Bundle Pack
	Robin Bundle Pack
	Harley Quinn’s Revenge
	Challenge Map Pack
	Arkham City Skins Pack

Batman: Arkham City - Game of the Year Edition packages new gameplay content, seven maps, three playable characters, and 12 skins beyond the original retail release: 
	Maps: Wayne Manor, Main Hall, Freight Train, Black Mask, The Joker's Carnival, Iceberg Long, and Batcave
	Playable Characters: Catwoman, Robin and Nightwing
	Skins: 1970s Batsuit, Year One Batman, The Dark Knight Returns, Earth One Batman, Batman Beyond Batman, Animated Batman, Sinestro Corps Batman, Long Halloween Catwoman, Animated Catwoman, Animated Robin, Red Robin and Animated Nightwing",
                            Discontinued = false,
                            Discount = 14f,
                            IsDeleted = false,
                            Key = "Batman: Arkham City - Game of the Year Edition",
                            Name = "Batman: Arkham City - Game of the Year Edition",
                            Price = 34.10m,
                            PublisherId = 1,
                            UnitInStock = (short)12
                        },
                        new
                        {
                            Id = 9,
                            Description = @"Penny Arcade’s “On the Rain-Slick Precipice of Darkness 4” concludes the saga of Tycho Brahe, Scion of The Long Project, and his almost certainly human partner Jonathan Gabriel. The world has been destroyed, but existence extends beyond this mortal plane in the gruesome Underhell! The new game expands considerably on its predecessor in size, scope and gameplay. Create the ultimate fighting force by recruiting bizarre, occasionally disgusting monsters and teaming them up with the best trainer for the job! 

Key Features
	Old - School RPG style mixed with modern design sensibilities!
	Bizarre and humorous story written by Penny Arcade & Zeboyd Games!
	Over twice as many area maps as the previous game!
	Explore the Underhell world(in all its traditional RPG glory) and discover its many secrets.
	No random battles!
	Music created by Hyperduck Soundworks(Dust: An Elysian Tail, Mojang's Scrolls)!
	Recruit bizarre & powerful monsters like a sentient vending machine, an evil ice cream cone, a bug - crow... thing, and more!
	Disrupt enemy attacks with powerful interrupt abilities!
	Rechargeable MP & items! Unleash your full power in every battle!",
                            Discontinued = false,
                            Discount = 2f,
                            IsDeleted = false,
                            Key = "Penny Arcade's On the Rain-Slick Precipice of Darkness 4",
                            Name = "Penny Arcade's On the Rain-Slick Precipice of Darkness 4",
                            Price = 22.30m,
                            PublisherId = 1,
                            UnitInStock = (short)54
                        },
                        new
                        {
                            Id = 10,
                            Description = @"From the creators of Bastion, Transistor is a sci-fi themed action RPG that invites you to wield an extraordinary weapon of unknown origin as you fight through a stunning futuristic city. Transistor seamlessly integrates thoughtful strategic planning into a fast-paced action experience, melding responsive gameplay and rich atmospheric storytelling. During the course of the adventure, you will piece together the Transistor's mysteries as you pursue its former owners. 

Key Features:	An all - new world from the team that created Bastion
	Configure the powerful Transistor with thousands of possible Function combinations
	Action - packed real - time combat fused with a robust strategic planning mode
	Vibrant hand - painted artwork in full 1080p resolution
	Original soundtrack changes dynamically as the action unfolds
	Hours of reactive voiceover create a deep and atmospheric story
	'Recursion' option introduces procedural battles after finishing the story
	Fully customizable controls custom - tailored for PC",
                            Discontinued = false,
                            Discount = 8f,
                            IsDeleted = false,
                            Key = "Transistor",
                            Name = "Transistor",
                            Price = 23.00m,
                            PublisherId = 1,
                            UnitInStock = (short)89
                        },
                        new
                        {
                            Id = 11,
                            Description = @"The lord of insanity, Cthulhu was all set to plunge the world into insanity and destruction when his powers were sealed by a mysterious sorcerer. The only way for him to break the curse is to become a true hero. Save the world to destroy it in an epic parody RPG journey of redemption, romance, and insanity!

Key features:
	Old school RPG style mixed with modern design sensibilities!
	Inflict insanity upon your opponents for fun and profit!
	6 - 10 hour quest with unlockable game modes & difficulty levels for increased replay value.
	Highlander mode – XP gains are quadrupled, but only one character can be brought into battle at a time!
	Score Attack mode – Gain points by defeating bosses at the lowest LV possible!
	Overkill – Jump to LV40 in a single battle! Perfect for replays and experimentation!
	Cthulhu's Angels mode – Remix mode with new playable characters, new dialogue, new bosses, and more!
	All of the great features players know and love from Breath of Death VII: The Beginning have returned – fast - paced gameplay, combo system, random encounter limits, branching LV - Ups, and more!",
                            Discontinued = false,
                            Discount = 6f,
                            IsDeleted = false,
                            Key = "Cthulhu Saves the World",
                            Name = "Cthulhu Saves the World",
                            Price = 34.29m,
                            PublisherId = 1,
                            UnitInStock = (short)13
                        },
                        new
                        {
                            Id = 12,
                            Description = @"The Flagship Turn-Based Strategy Game Returns
Become Ruler of the World by establishing and leading a civilization from the dawn of man into the space age: Wage war, conduct diplomacy, discover new technologies, go head - to - head with some of history’s greatest leaders and build the most powerful empire the world has ever known.

	INVITING PRESENTATION: Jump right in and play at your own pace with an intuitive interface that eases new players into the game. Veterans will appreciate the depth, detail and control that are highlights of the series.
	BELIEVABLE WORLD: Ultra realistic graphics showcase lush landscapes for you to explore, battle over and claim as your own.
	COMMUNITY & MULTIPLAYER: Compete with players all over the world or locally in LAN matches, mod the game in unprecedented ways, and install mods directly from an in-game community hub without ever leaving the game.
	WIDE SYSTEM COMPATIBILITY: Civilization V operates on many different systems, from high end desktops to many laptops.
	ALL NEW FEATURES: A new hex-based gameplay grid opens up exciting new combat and build strategies. City States become a new resource in your diplomatic battleground. An improved diplomacy system allows you to negotiate with fully interactive leaders.",
                            Discontinued = false,
                            Discount = 78f,
                            IsDeleted = false,
                            Key = "Sid Meier's Civilization® V",
                            Name = "Sid Meier's Civilization® V",
                            Price = 123.89m,
                            PublisherId = 1,
                            UnitInStock = (short)438
                        });
                });

            modelBuilder.Entity("GameStore.Dal.Entities.GameGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameGenres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            GenreId = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            GameId = 1,
                            GenreId = 7,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            GameId = 2,
                            GenreId = 7,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            GameId = 2,
                            GenreId = 13,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            GameId = 3,
                            GenreId = 6,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            GameId = 4,
                            GenreId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            GameId = 4,
                            GenreId = 16,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            GameId = 4,
                            GenreId = 9,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            GameId = 5,
                            GenreId = 16,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            GameId = 5,
                            GenreId = 17,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            GameId = 5,
                            GenreId = 7,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            GameId = 6,
                            GenreId = 8,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 13,
                            GameId = 6,
                            GenreId = 7,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 14,
                            GameId = 7,
                            GenreId = 9,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 15,
                            GameId = 7,
                            GenreId = 16,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 16,
                            GameId = 8,
                            GenreId = 7,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 17,
                            GameId = 8,
                            GenreId = 6,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 18,
                            GameId = 9,
                            GenreId = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 19,
                            GameId = 9,
                            GenreId = 16,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 20,
                            GameId = 10,
                            GenreId = 6,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 21,
                            GameId = 10,
                            GenreId = 16,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 22,
                            GameId = 10,
                            GenreId = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 23,
                            GameId = 11,
                            GenreId = 16,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 24,
                            GameId = 11,
                            GenreId = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 25,
                            GameId = 12,
                            GenreId = 1,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("GameStore.Dal.Entities.GamePlatformType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PlatformTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlatformTypeId");

                    b.ToTable("GamePlatformTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            IsDeleted = false,
                            PlatformTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            GameId = 1,
                            IsDeleted = false,
                            PlatformTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            GameId = 2,
                            IsDeleted = false,
                            PlatformTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            GameId = 2,
                            IsDeleted = false,
                            PlatformTypeId = 3
                        },
                        new
                        {
                            Id = 5,
                            GameId = 3,
                            IsDeleted = false,
                            PlatformTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            GameId = 3,
                            IsDeleted = false,
                            PlatformTypeId = 3
                        },
                        new
                        {
                            Id = 7,
                            GameId = 4,
                            IsDeleted = false,
                            PlatformTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            GameId = 4,
                            IsDeleted = false,
                            PlatformTypeId = 2
                        },
                        new
                        {
                            Id = 9,
                            GameId = 4,
                            IsDeleted = false,
                            PlatformTypeId = 3
                        },
                        new
                        {
                            Id = 10,
                            GameId = 4,
                            IsDeleted = false,
                            PlatformTypeId = 4
                        },
                        new
                        {
                            Id = 11,
                            GameId = 5,
                            IsDeleted = false,
                            PlatformTypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            GameId = 6,
                            IsDeleted = false,
                            PlatformTypeId = 1
                        },
                        new
                        {
                            Id = 13,
                            GameId = 6,
                            IsDeleted = false,
                            PlatformTypeId = 2
                        },
                        new
                        {
                            Id = 14,
                            GameId = 7,
                            IsDeleted = false,
                            PlatformTypeId = 1
                        },
                        new
                        {
                            Id = 15,
                            GameId = 7,
                            IsDeleted = false,
                            PlatformTypeId = 2
                        },
                        new
                        {
                            Id = 16,
                            GameId = 8,
                            IsDeleted = false,
                            PlatformTypeId = 3
                        },
                        new
                        {
                            Id = 17,
                            GameId = 8,
                            IsDeleted = false,
                            PlatformTypeId = 1
                        },
                        new
                        {
                            Id = 18,
                            GameId = 9,
                            IsDeleted = false,
                            PlatformTypeId = 3
                        },
                        new
                        {
                            Id = 19,
                            GameId = 9,
                            IsDeleted = false,
                            PlatformTypeId = 1
                        },
                        new
                        {
                            Id = 20,
                            GameId = 9,
                            IsDeleted = false,
                            PlatformTypeId = 2
                        },
                        new
                        {
                            Id = 21,
                            GameId = 10,
                            IsDeleted = false,
                            PlatformTypeId = 3
                        },
                        new
                        {
                            Id = 22,
                            GameId = 11,
                            IsDeleted = false,
                            PlatformTypeId = 4
                        },
                        new
                        {
                            Id = 23,
                            GameId = 11,
                            IsDeleted = false,
                            PlatformTypeId = 1
                        },
                        new
                        {
                            Id = 24,
                            GameId = 12,
                            IsDeleted = false,
                            PlatformTypeId = 1
                        });
                });

            modelBuilder.Entity("GameStore.Dal.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ParentGenreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "RTS",
                            ParentGenreId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "TBS",
                            ParentGenreId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Name = "Races"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Name = "Rally",
                            ParentGenreId = 6
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            Name = "Arcade",
                            ParentGenreId = 6
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            Name = "Formula",
                            ParentGenreId = 6
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            Name = "Off-road",
                            ParentGenreId = 6
                        },
                        new
                        {
                            Id = 11,
                            IsDeleted = false,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 12,
                            IsDeleted = false,
                            Name = "FPS",
                            ParentGenreId = 11
                        },
                        new
                        {
                            Id = 13,
                            IsDeleted = false,
                            Name = "TPS",
                            ParentGenreId = 11
                        },
                        new
                        {
                            Id = 15,
                            IsDeleted = false,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 16,
                            IsDeleted = false,
                            Name = "Puzzle & Skill"
                        },
                        new
                        {
                            Id = 17,
                            IsDeleted = false,
                            Name = "Misc."
                        });
                });

            modelBuilder.Entity("GameStore.Dal.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosedForEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSum")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GameStore.Dal.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.Property<decimal>("SumWithDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SumWithoutDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("GameStore.Dal.Entities.PlatformType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("PlatformTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Type = "PC"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Type = "PS3"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Type = "PS4"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Type = "Xbox360"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Type = "XboxONE"
                        });
                });

            modelBuilder.Entity("GameStore.Dal.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName")
                        .IsUnique()
                        .HasFilter("[CompanyName] IS NOT NULL");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Rockstar",
                            Description = "Rockstar Games, Inc. is an American video game publisher based in New York City. The company was established in December 1998 as a subsidiary of Take-Two Interactive, using the assets Take-Two had previously acquired from BMG Interactive. Founding members of the company were Sam and Dan Houser, Terry Donovan and Jamie King, who worked for Take-Two at the time, and of which the Houser brothers were previously executives at BMG Interactive. Sam Houser heads the studio as president.",
                            HomePage = "rockstar.com",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Blizzard",
                            Description = "Blizzard Entertainment is a PC, console, and mobile game developer known for its epic multiplayer titles including the Warcraft, Diablo, StarCraft, and Overwatch ...",
                            HomePage = "blizzard.com",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "EA Mobile",
                            Description = "EA Mobile Inc. is an American video game development studio of the publisher Electronic Arts (EA) for mobile platforms. ",
                            HomePage = "ea.com",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Wargaming",
                            Description = "Wargaming.net is a private company, offshore company, publisher and developer of computer games, mainly free-to-play MMO genre and near-game services for various platforms. The headquarters is located in Nicosia, Republic of Cyprus, the development centers are in Minsk (main), Kiev, St. Petersburg, Seattle, Chicago, Baltimore, Sydney, Helsinki, Austin and Prague.",
                            HomePage = "wargaming.com",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("GameStore.Dal.Entities.Comment", b =>
                {
                    b.HasOne("GameStore.Dal.Entities.Game", "Game")
                        .WithMany("Comments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameStore.Dal.Entities.Game", b =>
                {
                    b.HasOne("GameStore.Dal.Entities.Publisher", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameStore.Dal.Entities.GameGenre", b =>
                {
                    b.HasOne("GameStore.Dal.Entities.Game", "Game")
                        .WithMany("Genres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Dal.Entities.Genre", "Genre")
                        .WithMany("Games")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameStore.Dal.Entities.GamePlatformType", b =>
                {
                    b.HasOne("GameStore.Dal.Entities.Game", "Game")
                        .WithMany("PlatformTypes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Dal.Entities.PlatformType", "PlatformType")
                        .WithMany("Games")
                        .HasForeignKey("PlatformTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameStore.Dal.Entities.OrderItem", b =>
                {
                    b.HasOne("GameStore.Dal.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Dal.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
